name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd /var/www/test.agrosoft.uz
    - run: npm install
    - run: rm -rf .next
    - run: npm run build --if-present
    - run: pm2 reload your-app-name
      env:
        CI: true
        
