name: Deploy Next.js App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: centos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Deploy app
        uses: easingthemes/ssh-deploy@v2.2.6
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-public-key: ${{ secrets.SSH_PUBLIC_KEY }}
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          local-path: ./out
          remote-path: /var/www/test.agrosoft.uz
